### ISSUE TITLE
java.lang.NoSuchMethodError: 'java.lang.ClassLoader com.google.inject.internal.BytecodeGen.getClassLoader(java.lang.Class)' when using in Play 2.8.18

### ISSUE THREAD

**Issue by phelps-sg** [phelps-sg/play-hmac-signatures#11]
When using the play-hmac-signatures v.0.4.3 jar for Scala 2.13 with Java 11 (instead of Java 8) attempting to instantiate `SignatureVerifyAction` throws the following exception:

~~~
java.lang.NoSuchMethodError: 'java.lang.ClassLoader com.google.inject.internal.BytecodeGen.getClassLoader(java.lang.Class)'
at com.google.inject.assistedinject.FactoryProvider2.<init>(FactoryProvider2.java:358)
at com.google.inject.assistedinject.FactoryModuleBuilder$1.configure(FactoryModuleBuilder.java:316)
at com.google.inject.AbstractModule.configure(AbstractModule.java:66)
at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409)
~~~

**Comment by phelps-sg** [comment]
This could be caused by dependency conflict in guice versions.  Play uses 4.2.3 whereas play-hmac-signatures request latest version 5.1.0
